baseurl = "https://ranpeng.fun/"
title = "苒芃"
theme = ["blist"]

timeout = "90s"
timeZone = "Asia/Shanghai"
hasCJKLanguage = true

DefaultContentLanguage = "zh-cn"
DefaultContentLanguageInSubdir = false
[languages]
  [languages.zh-cn]
    contentDir = "content/" 
    weight = 1
    languageName = "中文"
    [languages.zh-cn.params]
      introTitle = "苒芃 - 分享我们的AI实践"
      introSubtitle = "探索AI+写作、编程、休闲游戏和股市的创新实践，助您洞见未来。关注我们，一起成长！"
      introPhoto = "/qrcode.png"
      logo = "/logo.png"

    [[languages.zh-cn.menu.main]]
        name = "首页"
        url = "/"
        weight = 1

    [[languages.zh-cn.menu.main]]
        name = "关于"
        url = "about"
        weight = 2

    [[languages.zh-cn.menu.main]]
        name = "标签"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = false

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
#  searchKeys = [
#    "tags",
#    "date",
#    "categories",
#    "summary",
#    "content",
#    "link",
#    "author"
#  ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - 苒芃科技 · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
#  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
#[params.comments]
#  # Supports disqus, giscus and utterances
#  # Check hugo docs for setting up disqus
#  system = "giscus"
#
#  # Options for giscus, exclude hyphens
#  repo = ""
#  repoid = ""
#  category = ""
#  categoryid = ""
#  mapping = ""
#  strict = ""
#  reactionsenabled = ""
#  emitmetadata = ""
#  inputposition = ""
#  theme = ""
#
#  # Options for utterances, exclude hyphens
#  # repo = ""
#  # issueterm = ""
#  # theme = ""

[build]
  writeStats = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

[params.homepage.social]
  title = "如果对您有帮助，请关注我们."
  description = "发送邮件: pistachio@ranpeng.fun"
